### PR TITLE
state repr model and RepresentationAgent

### PR DESCRIPTION
**Pull request by hnyu**
A state representation learning model used by PlaNet and Dreamer. Will report results of using it to train Breakout later. The model is basically a VAE. But because of some detail difference, I didn't use VAE as a component. 

I also created a new Agent class RepresentationAgent to use this representation model, to separate it from our master Agent for now.

### CODE REVIEW

**Comment by emailweixu** [comment]
Why not just add representation learning module to current Agent?

**Comment by hnyu** [comment]
> Why not just add representation learning module to current Agent?

Haven't figured out how to use the learned representation in the current Agent effectively because usually our policy/value networks directly accept raw observations as inputs. The learned latent representation is non-stationary and the benefit to the downstream policy/value networks is unclear at this point. I think we can add it to Agent after verifying its benefit.

It also makes sense to me that besides the master Agent, we have several other smaller-size agents that serve different purposes.

**Comment by emailweixu** [comment]
But this is exactly what you are doing in RepresentationAgent.

> Haven't figured out how to use the learned representation in the current Agent effectively because usually our policy/value networks directly accept raw observations as inputs. The learned latent representation is non-stationary and the benefit to the downstream policy/value networks is unclear at this point. I think we can add it to Agent after verifying its benefit.
> 
> It also makes sense to me that besides the master Agent, we have several other smaller-size agents that serve different purposes.

**Comment by hnyu** [comment]
> But this is exactly what you are doing in RepresentationAgent.
> 
> > Haven't figured out how to use the learned representation in the current Agent effectively because usually our policy/value networks directly accept raw observations as inputs. The learned latent representation is non-stationary and the benefit to the downstream policy/value networks is unclear at this point. I think we can add it to Agent after verifying its benefit.
> > It also makes sense to me that besides the master Agent, we have several other smaller-size agents that serve different purposes.

I was thinking that maybe we should first verify the effectiveness of a representation model and then integrated into our master Agent class, because that change will be more than here.

Right now I'm still debugging the model.

**Pull request closed without merging**
