### PR TITLE
avoid loading critic networks from state dict during deployment if critic_network_cls is None

### PR DESCRIPTION
**Pull request by le-horizon**

### CODE REVIEW

**Comment by le-horizon** [comment]
Addressed Break's concern about the unittest by passing in a config is_eval to RLAlgorithm.
Adjusted code according to the change.
@breakds PTAL.

**Review by breakds — APPROVED** [review]

**Comment by breakds** [comment]
I'd suggest @runjerry to also take a look

**Comment by le-horizon** [comment]
> I'd suggest @runjerry to also take a look

Oops, merged early.  @runjerry , could you take a look at this PR as well?  I'll fix as needed.  Thanks!

**Comment by runjerry** [comment]
> > I'd suggest @runjerry to also take a look
> 
> Oops, merged early. @runjerry , could you take a look at this PR as well? I'll fix as needed. Thanks!

Thanks Le for updating this! The PR looks good to me. 

I have only one further question: should we put a customized sac_algorithm under Hobot or change the general alf.sac_algorithm as it is? The reasons for this question are:

1. It seems that this is only needed for our current deployment design rather than general RL settings.
2. Since ``is_eval`` is provided as an option in the base class ``RLAlgorithm``, should we update all other alf rl algorithms that also use critic_networks or value_networks?

**Pull request merged**
