### PR TITLE
first upgrade clang-format to 9.0

### PR DESCRIPTION
**Pull request by hnyu**
otherwise the cnest PR CI won't pass. My desktop doesn't allow installing a version of 3.8 which is the current requirement.

### CODE REVIEW

**Comment by Haichao-Zhang** [comment]
If the docker image used by github ci is updated first, then is doesn't matter to separate this upgrade part or not?
In my understanding, merging this pr first won't make the CI pass on cnest. Instead, you might need to update the docker image first and then update this line
https://github.com/HorizonRobotics/alf/blob/c7c8832b9a55ed4f0faccd2eb54162ec4ebdb51b/.github/workflows/test.yml#L9

**Comment by hnyu** [comment]
> If the docker image used by github ci is updated first, then is doesn't matter to separate this upgrade part or not?
> In my understanding, merging this pr first won't make the CI pass on cnest. Instead, you might need to update the docker image first and then update this line
> https://github.com/HorizonRobotics/alf/blob/c7c8832b9a55ed4f0faccd2eb54162ec4ebdb51b/.github/workflows/test.yml#L9

I'm actually confused by our current CI setup everytime. It seems that the Dockerfile doesn't need to exist if we are pulling an alf docker from the docker hub?

**Comment by hnyu** [comment]
> If the docker image used by github ci is updated first, then is doesn't matter to separate this upgrade part or not?
> In my understanding, merging this pr first won't make the CI pass on cnest. Instead, you might need to update the docker image first and then update this line
> https://github.com/HorizonRobotics/alf/blob/c7c8832b9a55ed4f0faccd2eb54162ec4ebdb51b/.github/workflows/test.yml#L9

OK I'm confused every time by this. I thought somehow CI will automatically build an image given the Dockerfile. It's not quite smart or automatic I guess.

**Comment by Haichao-Zhang** [comment]
> OK I'm confused every time by this. I thought somehow CI will automatically build an image given the Dockerfile. It's not quite smart or automatic I guess.

Yes it is a bit mis-leading . Unfortunately, it won't build the image. The Dockerfile here is mainly used for versioning/backing-up purpose.

**Pull request closed without merging**
