### PR TITLE
remove some old tf files

### PR DESCRIPTION
**Pull request by hnyu**
These files will no longer be needed or have been converted.

### CODE REVIEW

**Review by emailweixu — COMMENTED** [review]
action_encoder.py is used by merlin_algorithm

**Comment by hnyu** [comment]
> action_encoder.py is used by merlin_algorithm

Can we just use EmbeddingPreprocessor to achieve a similar purpose?

**Review by le-horizon — DISMISSED** [review]
Looks good to me.  Please address other reviewers' comments before push.

Thanks,
Le

**Comment by emailweixu** [comment]
> > action_encoder.py is used by merlin_algorithm
> 
> Can we just use EmbeddingPreprocessor to achieve a similar purpose?

SimpleActionEncoder is parameterless can can handle nested action. It is easier to use.

**Review by emailweixu — APPROVED** [review]

**Pull request merged**
