### PR TITLE
Add example capacity scheuling conf and train_play_test

### PR DESCRIPTION
**Pull request by Haichao-Zhang**
Add an example conf to illustrate its usage.

image

### CODE REVIEW

**Comment by Haichao-Zhang** [comment]
@hnyu you can use this conf for testing, and you can set a smaller value for eval_interval. I have tested it with eval_interval=1 without any problem.

**Comment by hnyu** [comment]
Confirmed that if I replace AdamTF with Adam, then the error occurs. Is capacity scheduling only compatible with AdamTF at this moment?

**Comment by Haichao-Zhang** [comment]
> Confirmed that if I replace AdamTF with Adam, then the error occurs. Is capacity scheduling only compatible with AdamTF at this moment?

Should be compatible with all optimizers.
I also tested with Adam yesterday. No problem as well.

Run again and screenshot:

image

image

**Comment by hnyu** [comment]
Seems that for torch>2, Adam has some changes that make this crash happen. I thought I was using the docker image with torch1.11, but in fact it was torch2.1. So if I use docker with torch1.11, the error is gone. 

You can try loading horizonrobotics/cuda:11.8-torch2.1-py3.8-ubuntu20.04 and see the error happening.

**Comment by Haichao-Zhang** [comment]
Good that you can run without problem under the standard setting (as in hobot).

It is possible that new changes (especially API related ones) from torch team on the optimizers may cause problems.
This is a general issue if the API changes from torch team is not backward compatible.

**Review by hnyu — APPROVED** [review]
For anyone with torch>2, if using capacity scheduling, make sure to use AdamTF instead of Adam at this moment.

**Comment by Haichao-Zhang** [comment]
> For anyone with torch>2, if using capacity scheduling, make sure to use AdamTF instead of Adam at this moment.

Yes. The reason is that AdamTF is implemented by ourselves and is not affected by torch's changes on optimizers.

**Pull request merged**
