### PR TITLE
exp is on CPU, needs to be transferred to cuda before torch.where

### PR DESCRIPTION
**Pull request by le-horizon**
@hnyu this should fix the problem.  I tested locally.

Thanks,
Le

### CODE REVIEW

**Comment by hnyu** [comment]
Why exp is on CPU? The metrics during training seems OK, but just fails for eval? By default the tensors should use the default device which is CUDA.

**Comment by le-horizon** [comment]
No idea why.  @emailweixu do you know why experience for eval env contains CPU tensors instead of GPU?

**Comment by emailweixu** [comment]
> No idea why. @emailweixu do you know why experience for eval env contains CPU tensors instead of GPU?

training uses ProcessEnvironment, which explicitly convert to cuda
eval uses ThreadTorchEnvironment.

**Comment by emailweixu** [comment]
We should fix ThreadTorchEnvironment intead.

**Comment by le-horizon** [comment]
> We should fix ThreadTorchEnvironment intead.

@runjerry could you help explicitly convert experience tensors to cuda? as is done in ProcessEnvironment?

Thanks!

**Comment by hnyu** [comment]
Refer to #474

**Pull request closed without merging**
