### PR TITLE
[Preview] Use cnest from pypi and remove embedded cnest

### PR DESCRIPTION
**Pull request by breakds**
# Motivation

This is to address #970. Note that we have already created a separate cnest repo and [hosted it on pypi](https://pypi.org/project/cnest/).

# Change

1. Remove the embedded pypi
2. In `setup.py` use the pypi version

### CODE REVIEW

**Comment by hnyu** [comment]
Please remember to remove two lines in .ci-cd/build.sh

**Comment by breakds** [comment]
> Please remember to remove two lines in .ci-cd/build.sh

Yep, I realized that after seeing the failure. Updated CI/CD right away.

**Comment by breakds** [comment]
I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.

**Comment by hnyu** [comment]
> I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.

Yeah you need to add 'cnest' pypi to .ci-cd/requirements.txt and re-build the docker image for github CI test. Then push it to horizonrobotics/alf:0.0.6-pytorch1.8-python3.7

Make sure to open another PR first for this docker change. Otherwise the current PR will still fail.

**Comment by breakds** [comment]
> > I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.
> 
> Yeah you need to add 'cnest' pypi to .ci-cd/requirements.txt and re-build the docker image for github CI test. Then push it to horizonrobotics/alf:0.0.6-pytorch1.8-python3.7
> 
> Make sure to open another PR first for this docker change. Otherwise the current PR will still fail.

I tried building the docker image with `docker build -f Dockerfile.cpu .`, and it failed on getting torch:

```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.8.1+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (169.1 MB)
Collecting torchvision==0.9.1+cpu
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (13.3 MB)
ERROR: Could not find a version that satisfies the requirement torchtext==0.9.1+cpu (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0.dev20210222, 0.9.0, 0.9.1, 0.10.0)
ERROR: No matching distribution found for torchtext==0.9.1+cpu
```

Is this because `pypi` no longer offers `+gpu` version? (Just in case you have come across this before)

**Comment by hnyu** [comment]
> > > I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.
> > 
> > 
> > Yeah you need to add 'cnest' pypi to .ci-cd/requirements.txt and re-build the docker image for github CI test. Then push it to horizonrobotics/alf:0.0.6-pytorch1.8-python3.7
> > Make sure to open another PR first for this docker change. Otherwise the current PR will still fail.
> 
> I tried building the docker image with `docker build -f Dockerfile.cpu .`, and it failed on getting torch:
> 
> ```
> Looking in links: https://download.pytorch.org/whl/torch_stable.html
> Collecting torch==1.8.1+cpu
>   Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (169.1 MB)
> Collecting torchvision==0.9.1+cpu
>   Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (13.3 MB)
> ERROR: Could not find a version that satisfies the requirement torchtext==0.9.1+cpu (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0.dev20210222, 0.9.0, 0.9.1, 0.10.0)
> ERROR: No matching distribution found for torchtext==0.9.1+cpu
> ```
> 
> Is this because `pypi` no longer offers `+gpu` version? (Just in case you have come across this before)

You mean "+cpu" version? CI doesn't require GPUs. 

Note that only torchtext-cpu is not found. torch and torchvision are fine. This is weird because @Haichao-Zhang built a docker using this file three months ago. Maybe fix it if you can?

**Comment by breakds** [comment]
> > > > I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.
> > > 
> > > 
> > > Yeah you need to add 'cnest' pypi to .ci-cd/requirements.txt and re-build the docker image for github CI test. Then push it to horizonrobotics/alf:0.0.6-pytorch1.8-python3.7
> > > Make sure to open another PR first for this docker change. Otherwise the current PR will still fail.
> > 
> > 
> > I tried building the docker image with `docker build -f Dockerfile.cpu .`, and it failed on getting torch:
> > ```
> > Looking in links: https://download.pytorch.org/whl/torch_stable.html
> > Collecting torch==1.8.1+cpu
> >   Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (169.1 MB)
> > Collecting torchvision==0.9.1+cpu
> >   Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (13.3 MB)
> > ERROR: Could not find a version that satisfies the requirement torchtext==0.9.1+cpu (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0.dev20210222, 0.9.0, 0.9.1, 0.10.0)
> > ERROR: No matching distribution found for torchtext==0.9.1+cpu
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this because `pypi` no longer offers `+gpu` version? (Just in case you have come across this before)
> 
> You mean "+cpu" version? CI doesn't require GPUs.
> 
> Note that only torchtext-cpu is not found. torch and torchvision are fine. This is weird because @Haichao-Zhang built a docker using this file three months ago. Maybe fix it if you can?

3 Months are long within python community's timeline :) Sure, let me check and experiment.

**Comment by Haichao-Zhang** [comment]
> > > > > I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.
> > > > 
> > > > 
> > > > Yeah you need to add 'cnest' pypi to .ci-cd/requirements.txt and re-build the docker image for github CI test. Then push it to horizonrobotics/alf:0.0.6-pytorch1.8-python3.7
> > > > Make sure to open another PR first for this docker change. Otherwise the current PR will still fail.
> > > 
> > > 
> > > I tried building the docker image with `docker build -f Dockerfile.cpu .`, and it failed on getting torch:
> > > ```
> > > Looking in links: https://download.pytorch.org/whl/torch_stable.html
> > > Collecting torch==1.8.1+cpu
> > >   Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (169.1 MB)
> > > Collecting torchvision==0.9.1+cpu
> > >   Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (13.3 MB)
> > > ERROR: Could not find a version that satisfies the requirement torchtext==0.9.1+cpu (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0.dev20210222, 0.9.0, 0.9.1, 0.10.0)
> > > ERROR: No matching distribution found for torchtext==0.9.1+cpu
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is this because `pypi` no longer offers `+gpu` version? (Just in case you have come across this before)
> > 
> > 
> > You mean "+cpu" version? CI doesn't require GPUs.
> > Note that only torchtext-cpu is not found. torch and torchvision are fine. This is weird because @Haichao-Zhang built a docker using this file three months ago. Maybe fix it if you can?
> 
> 3 Months are long within python community's timeline :) Sure, let me check and experiment.

Can give a try on using "torchtext==0.9.1" without "+cpu"

**Comment by breakds** [comment]
> > > > > > I think there are still something wrong about setting up the environment for CI/CD. Will do some research later.
> > > > > 
> > > > > 
> > > > > Yeah you need to add 'cnest' pypi to .ci-cd/requirements.txt and re-build the docker image for github CI test. Then push it to horizonrobotics/alf:0.0.6-pytorch1.8-python3.7
> > > > > Make sure to open another PR first for this docker change. Otherwise the current PR will still fail.
> > > > 
> > > > 
> > > > I tried building the docker image with `docker build -f Dockerfile.cpu .`, and it failed on getting torch:
> > > > ```
> > > > Looking in links: https://download.pytorch.org/whl/torch_stable.html
> > > > Collecting torch==1.8.1+cpu
> > > >   Downloading https://download.pytorch.org/whl/cpu/torch-1.8.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (169.1 MB)
> > > > Collecting torchvision==0.9.1+cpu
> > > >   Downloading https://download.pytorch.org/whl/cpu/torchvision-0.9.1%2Bcpu-cp37-cp37m-linux_x86_64.whl (13.3 MB)
> > > > ERROR: Could not find a version that satisfies the requirement torchtext==0.9.1+cpu (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0.dev20210222, 0.9.0, 0.9.1, 0.10.0)
> > > > ERROR: No matching distribution found for torchtext==0.9.1+cpu
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Is this because `pypi` no longer offers `+gpu` version? (Just in case you have come across this before)
> > > 
> > > 
> > > You mean "+cpu" version? CI doesn't require GPUs.
> > > Note that only torchtext-cpu is not found. torch and torchvision are fine. This is weird because @Haichao-Zhang built a docker using this file three months ago. Maybe fix it if you can?
> > 
> > 
> > 3 Months are long within python community's timeline :) Sure, let me check and experiment.
> 
> Can give a try on using "torchtext==0.9.1" without "+cpu"

I was able to build the docker image without `+cpu`. Maybe they combined the gpu and nogpu into one release now.

**Review by hnyu — APPROVED** [review]

**Pull request merged**
