### PR TITLE
A tool to conveniently create a docker-based environment that resembles the CI env

### PR DESCRIPTION
**Pull request by breakds**
# Motivation

There are certain cases when you want to debug code and run unit tests or sanity check while

1. CI failed in a way that we do not anticipate because the CI environment is different from our dev environment
2. You might not have an already setup alf dev environment on some other laptop/workstation

In those cases we probably want to create  a development environment that resembles the CI environment.

# Solution

In this PR a tool `box.sh` is implemented to quickly throw such an environment to you. It is a bash script and the only dependency is `docker`.

# Testing

See the video:

alf-dev-box

### CODE REVIEW

**Review by le-horizon — COMMENTED** [review]
Nice tool to have.  Thanks for doing it Break!

The gif file is helpful, but maybe a bit large, and not very easy to control viewing.  Maybe upload to youtube and add a link here is better?

Thanks,
Le

**Comment by breakds** [comment]
> Nice tool to have. Thanks for doing it Break!
> 
> The gif file is helpful, but maybe a bit large, and not very easy to control viewing. Maybe upload to youtube and add a link here is better?
> 
> Thanks, Le

Ah yep it is huge ... Sorry about that. I have removed the gif from the commit. It it not that necessary anyway :)

**Review by le-horizon — APPROVED** [review]
LG

**Comment by breakds** [comment]
> LG

Ty for the prompt review!

**Pull request merged**
