### PR TITLE
increment global step every update

### PR DESCRIPTION
**Pull request by witwolf**

### CODE REVIEW

**Comment by hnyu** [comment]
The original definition of an "iteration" is once every rollout, I believe. This will change that definition. But from the perspective of summary, I think this makes more sense. @emailweixu

**Comment by hnyu** [comment]
If there are multiple summaries between two rollouts, will the reward curve look weird? For example, duplicate points that cause flat curve segments.

**Comment by witwolf** [comment]
> If there are multiple summaries between two rollouts, will the reward curve look weird? For example, duplicate points that cause flat curve segments.

Yes,  it will happen for metrics curve （AverageReturn, AverageEpisodeLength,EvnStep .. Update multiple times without collecting new data) . Modifying this is mainly because it’s helpful to summary for every update (summay_interval=1) when debugging

**Comment by emailweixu** [comment]
Perhaps separate metric summary fro training summary?

**Comment by witwolf** [comment]
> Perhaps separate metric summary fro training summary?

separated from training summary, only summary metric after rollout

**Pull request merged**
