### PR TITLE
render_heatmap_fast

### PR DESCRIPTION
**Pull request by emailweixu**
Different from the existing render_heatmap(), this function does not use matplotlib and is much faster and does not affect the video recording speed.

The following is an example of rendered multiple heatmap (ignore those read ellipses and black dots.)

image

### CODE REVIEW

**Comment by hnyu** [comment]
Not quite sure about the strip on the left. Is that the value bar?

**Comment by emailweixu** [comment]
> Not quite sure about the strip on the left. Is that the value bar?

It's the color bar representing the color of different value (i.e. different position in the bar).

**Comment by hnyu** [comment]
> > Not quite sure about the strip on the left. Is that the value bar?
> 
> It's the color bar representing the color of different value (i.e. different position in the bar).

The color bar should has a gradually changing value range? Somehow the bars in the figure have a sudden change from white to black, which is confusing.

**Comment by emailweixu** [comment]
> > > Not quite sure about the strip on the left. Is that the value bar?
> > 
> > 
> > It's the color bar representing the color of different value (i.e. different position in the bar).
> 
> The color bar should has a gradually changing value range? Somehow the bars in the figure have a sudden change from white to black, which is confusing.

If you look carefully, you can notice the change is not abrupt, though it is quite fast. This is because typically, the range of the value in the heatmap at one instant is quite small compared to the predefined range.

**Review by hnyu — APPROVED** [review]

**Pull request merged**
