### PR TITLE
correct episode_length during play

### PR DESCRIPTION
**Pull request by hnyu**
before the length output by logging is always missing one, which is confusing

### CODE REVIEW

**Comment by emailweixu** [comment]
In metric, the last step is not counted for episode length

**Comment by hnyu** [comment]
> In metric, the last step is not counted for episode length

Just checked, I think the metric does count the last step for episode length, which is also consistent with what I observe in my training TB (it doesn't count the first step, however). There the robotics runs always has an episode length of 50. When I played, it always says episode_length=49. 

(In our TimeLimit wrapper, `episode_length` means how many steps the agent takes. So for an episode of length `N`, there are `N+1` time steps involved. )

I believe making this quantity--either in TB or displayed by logging--consistent with max_episode_steps would be better. Some key statistics, like the final success signal might be what the user want to emphasize on. It'll be confusing if the length displayed is one missing.

**Comment by emailweixu** [comment]
> > In metric, the last step is not counted for episode length
> 
> Just checked, I think the metric does count the last step for episode length, which is also consistent with what I observe in my training TB (it doesn't count the first step, however). There the robotics runs always has an episode length of 50. When I played, it always says episode_length=49.
> 
> (In our TimeLimit wrapper, `episode_length` means how many steps the agent takes. So for an episode of length `N`, there are `N+1` time steps involved. )
> 
> I believe making this quantity--either in TB or displayed by logging--consistent with max_episode_steps would be better. Some key statistics, like the final success signal might be what the user want to emphasize on. It'll be confusing if the length displayed is one missing.

Actually, It's the first step not counted for episode length.

**Comment by hnyu** [comment]
> > > In metric, the last step is not counted for episode length
> > 
> > 
> > Just checked, I think the metric does count the last step for episode length, which is also consistent with what I observe in my training TB (it doesn't count the first step, however). There the robotics runs always has an episode length of 50. When I played, it always says episode_length=49.
> > (In our TimeLimit wrapper, `episode_length` means how many steps the agent takes. So for an episode of length `N`, there are `N+1` time steps involved. )
> > I believe making this quantity--either in TB or displayed by logging--consistent with max_episode_steps would be better. Some key statistics, like the final success signal might be what the user want to emphasize on. It'll be confusing if the length displayed is one missing.
> 
> Actually, It's the first step not counted for episode length.

Right, it's the first `time_step` that's ignored. But the total episode length in metric is still equal to `max_episode_steps` (number of action steps). (#time_steps = episode_length + 1). In our TimeLimit wrapper, `max_episode_steps` means number of action steps, not number of time steps.

**Review by emailweixu — APPROVED** [review]

**Pull request merged**
